---
title: "Midterm Take Home Portion"
author: "Jenn Lewis, Tamara Niella"
date: "4/27/2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
#install.packages("glue")
#install.packages("pracma")
library(glue)
library(rio)
library(purrr)
library(tidyverse)
library(pracma)

```

```{r Part A 1}
#Function to download data from link
download_file <- function(year) {
    link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
    rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

#Load data from multiple years and bind into single data frame
data <- map_df(15:18, download_file, .id = "year_link")

#Clean Data
data %<>%
  #clean names
  janitor::clean_names() %>%
  #filter for white and hispanic/latino students
  filter(student_group == "White" | 
         student_group == "Hispanic/Latino") %>%
  #select variables, drop percentages and collapsed levels
  select(academic_year,
         district,
         school,
         student_group,
         grade_level,
         starts_with("number_level")) %>%
  #gather number_level data to be two columns, level and n
  gather("level", "n", starts_with("number_level")) %>%
  #Convert level to a number, remove number_level_
  mutate(level = parse_number(level)) %>%
  #remove missing data
  filter(!is.na(n))

#Convert variables to factors
data <- data %>%
  mutate(academic_year = as.factor(academic_year),
         level = as.factor(level), 
         grade_level = as.factor(grade_level))%>%
  mutate(grade_level = str_replace_all(grade_level, "Grade", ""))

```


```{r Part A Question 2}
#Calculate the cumulative n for each school by student_group, grade, and academic_year.
data <- data %>%
  #need to arrange data before grouping 
  arrange(school,student_group, grade_level, academic_year, level) %>% 
  #group data
  group_by(school,student_group, grade_level, academic_year) %>%
  #create cn variable
  mutate(cn = cumsum(n))

```



```{r Part A Question 3}
#Reformat the data so it looks like the below, removing n and filling by cn. Remove rows that have missing data for either student group.
data %<>%
  #drop n column
  select(everything(), -n) %>%
  #spread the student_group out into two columns
  spread(student_group, cn) %>%
  #clean names
  janitor::clean_names() %>%
  #filter out missing data
  drop_na(white)%>%
  drop_na(hispanic_latino)
  

```

```{r Part B Question 1}
gap <- function(data, ref, foc) {
    x <- data[[ref]]
    y <- data[[foc]]
    auc <- pracma::trapz(y / y[length(x)],
                         x / x[length(x)])
    sqrt(2)*qnorm(auc)
}



#Estimate an achievement gap effect size for every school in the state that reported data on both student groups (i.e., using the data we created above), for each grade level in each academic year.



# nesting: 
nested_data <- data %>%
  nest(-academic_year, -school, -grade_level)

#create achievement gap effect size by looping through each data frame
nested_data <- nested_data%>% 
  mutate(es = map_dbl(data, gap, "white", "hispanic_latino"))


```

# Part B: Question 2 

```{r Part B Question 2}

#I need to get the district info so I create a function 
district_f<- function (a) { 
  a[["district"]][1]}

#prepare data
dat_b2 <- nested_data %>%
  drop_na()%>%
  mutate(district = map_chr(data, district_f))%>%
  mutate(district = str_replace_all(district, "SD", "")) %>%
  select(-data) %>% 
  group_by(school, district, academic_year) %>% 
  nest() %>% 
  slice(1:100)

plotsB <- dat_b2 %>% 
  mutate(plot = pmap(list(data, school, district, academic_year), ~
          ggplot(..1, aes(grade_level, es, fill = es)) +
          geom_col() + 
          scale_fill_distiller(palette = "YlGn")+
          coord_flip() + 
          geom_hline(yintercept = 0, size = 1, color = "Blue") +
          theme(legend.position = "bottom", legend.key.width = unit(3, "cm"), legend.title = element_blank()) +
          theme_minimal() +
          labs(title = glue("Achievement Gap Estimates: {..2}"), subtitle = "Students coded as White as compared to those coded as Hispanic/Latino\n", caption = glue("{..4} School year, {..3} School District, Oregon"), y = "\nEffect Size", x = "Grade\n")))

#lets look at the first 5
plotsB$plot[1:5]
```

# Part B Question 3 

```{r Part B question 3}

plotsB2 <- plotsB%>% slice(1:20)

save <- plotsB2 %>% 
  unite(file, school, academic_year, sep = "_")

fs::dir_create(here::here("Plots"))

files <- save$file

plot_s<- save$plot

path <- here::here("Plots", glue("{files}.png"))

walk2(path, plot_s, ggsave,
      width = 10, 
      height = 7.5,
      dpi = 600)

```


